server {
    listen 80;
    listen [::]:80;
    server_name learn.stephenarthur.org h5p.stephenarthur.org;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/local/lsws/Example/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
