import type { AdmissionApplication } from "./types";

export const admissionApplications: AdmissionApplication[] = [
  {
    id: "application-ama",
    tenantId: "tenant-greenfield",
    applicationNumber: "GA-2026-0142",
    applicant: {
      dateOfBirth: "2014-03-18",
      firstName: "Ama",
      lastName: "Ofori",
      previousSchool: "North Ridge Basic School",
    },
    guardian: {
      email: "efua.ofori@example.com",
      fullName: "Efua Ofori",
      phone: "+233 24 518 2740",
      relationship: "Mother",
    },
    desiredClassGroupId: "class-jhs1-blue",
    status: "under-review",
    submittedAt: "2026-07-19",
    submittedDocumentTypes: [
      "birth-certificate",
      "previous-report",
      "passport-photo",
    ],
    review: {
      reviewerId: "staff-admissions-1",
      startedAt: "2026-07-21",
    },
  },
  {
    id: "application-kojo",
    tenantId: "tenant-greenfield",
    applicationNumber: "GA-2026-0149",
    applicant: {
      dateOfBirth: "2013-11-02",
      firstName: "Kojo",
      lastName: "Asare",
      previousSchool: "St. Martin's Preparatory",
    },
    guardian: {
      email: "kwesi.asare@example.com",
      fullName: "Kwesi Asare",
      phone: "+233 20 773 1182",
      relationship: "Father",
    },
    desiredClassGroupId: "class-jhs2-gold",
    status: "submitted",
    submittedAt: "2026-07-22",
    submittedDocumentTypes: ["birth-certificate", "previous-report"],
  },
  {
    id: "application-sena",
    tenantId: "tenant-greenfield",
    applicationNumber: "GA-2026-0138",
    applicant: {
      dateOfBirth: "2012-06-27",
      firstName: "Sena",
      lastName: "Dovlo",
      previousSchool: "Tema Parents' Association School",
    },
    guardian: {
      email: "mavis.dovlo@example.com",
      fullName: "Mavis Dovlo",
      phone: "+233 27 419 6503",
      relationship: "Mother",
    },
    desiredClassGroupId: "class-jhs2-gold",
    status: "offered",
    submittedAt: "2026-07-16",
    submittedDocumentTypes: [
      "birth-certificate",
      "previous-report",
      "passport-photo",
    ],
    review: {
      reviewerId: "staff-admissions-1",
      startedAt: "2026-07-18",
    },
    decision: {
      decidedAt: "2026-07-21",
      decidedBy: "staff-admissions-1",
      decision: "offered",
      note: "Strong previous report and successful placement interview.",
      offerExpiresAt: "2026-08-08",
    },
  },
  {
    id: "application-yaw",
    tenantId: "tenant-greenfield",
    applicationNumber: "GA-2026-0121",
    applicant: {
      dateOfBirth: "2011-01-09",
      firstName: "Yaw",
      lastName: "Boateng",
      previousSchool: "Victory International School",
    },
    guardian: {
      email: "adwoa.boateng@example.com",
      fullName: "Adwoa Boateng",
      phone: "+233 55 206 9114",
      relationship: "Guardian",
    },
    desiredClassGroupId: "class-shs1-arts",
    status: "accepted",
    submittedAt: "2026-07-12",
    submittedDocumentTypes: [
      "birth-certificate",
      "previous-report",
      "passport-photo",
      "medical-note",
    ],
    review: {
      reviewerId: "staff-admissions-2",
      startedAt: "2026-07-14",
    },
    decision: {
      decidedAt: "2026-07-17",
      decidedBy: "staff-admissions-2",
      decision: "offered",
      note: "Offer approved for General Arts.",
      offerExpiresAt: "2026-08-02",
    },
    offerAcceptance: {
      acceptedAt: "2026-07-22",
      acceptedByGuardianId: "guardian-yaw",
    },
  },
  {
    id: "application-abena",
    tenantId: "tenant-greenfield",
    applicationNumber: "GA-2026-0108",
    applicant: {
      dateOfBirth: "2014-09-05",
      firstName: "Abena",
      lastName: "Owusu",
      previousSchool: "Datus Complex School",
    },
    guardian: {
      email: "joana.owusu@example.com",
      fullName: "Joana Owusu",
      phone: "+233 26 802 1775",
      relationship: "Mother",
    },
    desiredClassGroupId: "class-jhs1-blue",
    status: "enrolled",
    submittedAt: "2026-07-06",
    submittedDocumentTypes: [
      "birth-certificate",
      "previous-report",
      "passport-photo",
    ],
    review: {
      reviewerId: "staff-admissions-1",
      startedAt: "2026-07-08",
    },
    decision: {
      decidedAt: "2026-07-11",
      decidedBy: "staff-admissions-1",
      decision: "offered",
      note: "Admission approved.",
      offerExpiresAt: "2026-07-28",
    },
    offerAcceptance: {
      acceptedAt: "2026-07-15",
      acceptedByGuardianId: "guardian-abena",
    },
  },
];
