/* Generated by scripts/generate-learning-schema.ts from db/schema.ts.
   Do not edit by hand: regenerate with

     npm run schema:generate

   Storage types mirror the SQLite originals on purpose — see the generator for
   why. Tables already created by db/postgres.ts are not repeated here.

   This is a TypeScript module rather than a .sql file so that it is bundled
   and traced like any other import. A .sql read at runtime through
   import.meta.url does not reliably survive the Next standalone build that
   the Docker image is built from. */

export const learningSchema = `CREATE TABLE IF NOT EXISTS "subjects" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
);

CREATE TABLE IF NOT EXISTS "subject_offerings" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "subject_id" text NOT NULL,
  "class_group_id" text NOT NULL,
  "class_name" text NOT NULL,
  "academic_year_id" text NOT NULL,
  "requirement" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("subject_id") REFERENCES "subjects" ("id")
);

CREATE TABLE IF NOT EXISTS "assessments" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "author_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "current_version" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("author_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assessment_attempts" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assessment_id" text NOT NULL,
  "assessment_version" bigint NOT NULL,
  "learner_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'in-progress',
  "question_order" text NOT NULL DEFAULT '[]',
  "started_at" text NOT NULL,
  "deadline_at" text NOT NULL,
  "submitted_at" text,
  "auto_marks" bigint NOT NULL DEFAULT 0,
  "manual_marks" bigint NOT NULL DEFAULT 0,
  "maximum_marks" bigint NOT NULL,
  "released_at" text,
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assessment_versions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assessment_id" text NOT NULL,
  "version" bigint NOT NULL,
  "title" text NOT NULL,
  "purpose" text NOT NULL,
  "instructions" text NOT NULL DEFAULT '',
  "time_limit_minutes" bigint NOT NULL,
  "pass_mark_percent" bigint NOT NULL,
  "attempts_allowed" bigint NOT NULL DEFAULT 1,
  "shuffle_questions" bigint NOT NULL DEFAULT 0,
  "feedback_policy" text NOT NULL DEFAULT 'after-release',
  "status" text NOT NULL DEFAULT 'draft',
  "published_at" text,
  "created_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "question_bank_items" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "author_person_id" text NOT NULL,
  "type" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "difficulty" text NOT NULL DEFAULT 'standard',
  "topic" text NOT NULL,
  "tags" text NOT NULL DEFAULT '[]',
  "current_version" bigint NOT NULL DEFAULT 1,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("author_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "question_versions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "question_id" text NOT NULL,
  "version" bigint NOT NULL,
  "prompt" text NOT NULL,
  "options" text NOT NULL DEFAULT '[]',
  "answer_key" text NOT NULL DEFAULT '{}',
  "rationale" text NOT NULL DEFAULT '',
  "media" text,
  "formula" text,
  "marks" bigint NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "created_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("question_id") REFERENCES "question_bank_items" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assessment_questions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assessment_version_id" text NOT NULL,
  "question_version_id" text NOT NULL,
  "position" bigint NOT NULL,
  "marks" bigint NOT NULL,
  "required" bigint NOT NULL DEFAULT 1,
  "snapshot" text NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assessment_version_id") REFERENCES "assessment_versions" ("id"),
  FOREIGN KEY ("question_version_id") REFERENCES "question_versions" ("id")
);

CREATE TABLE IF NOT EXISTS "assessment_responses" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "attempt_id" text NOT NULL,
  "question_version_id" text NOT NULL,
  "response" text NOT NULL DEFAULT '{}',
  "flagged" bigint NOT NULL DEFAULT 0,
  "auto_marks" bigint NOT NULL DEFAULT 0,
  "manual_marks" bigint,
  "marking_status" text NOT NULL DEFAULT 'unanswered',
  "feedback" text,
  "marked_by_person_id" text,
  "marked_at" text,
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("attempt_id") REFERENCES "assessment_attempts" ("id"),
  FOREIGN KEY ("question_version_id") REFERENCES "question_versions" ("id"),
  FOREIGN KEY ("marked_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assignments" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "author_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "current_version" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("author_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assignment_submissions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assignment_id" text NOT NULL,
  "assignment_version" bigint NOT NULL,
  "learner_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'not-started',
  "response_text" text NOT NULL DEFAULT '',
  "submitted_at" text,
  "marked_by_person_id" text,
  "marked_at" text,
  "total_points" bigint,
  "feedback" text,
  "released_at" text,
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("marked_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "assignment_versions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assignment_id" text NOT NULL,
  "version" bigint NOT NULL,
  "title" text NOT NULL,
  "brief" text NOT NULL,
  "opens_at" text NOT NULL,
  "due_at" text NOT NULL,
  "maximum_points" bigint NOT NULL,
  "submission_mode" text NOT NULL,
  "status" text NOT NULL,
  "published_at" text,
  "created_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assignment_id") REFERENCES "assignments" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "attendance_sessions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "class_group_id" text NOT NULL,
  "session_date" text NOT NULL,
  "mode" text NOT NULL,
  "timetable_entry_id" text,
  "status" text NOT NULL DEFAULT 'draft',
  "taken_by_person_id" text NOT NULL,
  "submitted_at" text,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("taken_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "attendance_records" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "session_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "code" text NOT NULL,
  "note" text NOT NULL DEFAULT '',
  "recorded_by_person_id" text NOT NULL,
  "recorded_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("session_id") REFERENCES "attendance_sessions" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("recorded_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "attendance_corrections" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "attendance_record_id" text NOT NULL,
  "previous_code" text NOT NULL,
  "new_code" text NOT NULL,
  "reason" text NOT NULL,
  "corrected_by_person_id" text NOT NULL,
  "corrected_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("attendance_record_id") REFERENCES "attendance_records" ("id"),
  FOREIGN KEY ("corrected_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "curriculum_standards" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "code" text NOT NULL,
  "strand" text NOT NULL,
  "sub_strand" text NOT NULL,
  "description" text NOT NULL,
  "position" bigint NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id")
);

CREATE TABLE IF NOT EXISTS "curriculum_units" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "title" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "term" text NOT NULL,
  "position" bigint NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id")
);

CREATE TABLE IF NOT EXISTS "grading_periods" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "academic_year_id" text NOT NULL,
  "name" text NOT NULL,
  "starts_on" text NOT NULL,
  "ends_on" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "policy_version" bigint NOT NULL DEFAULT 1,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
);

CREATE TABLE IF NOT EXISTS "grade_categories" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "period_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "name" text NOT NULL,
  "kind" text NOT NULL,
  "weight_percent" bigint NOT NULL,
  "position" bigint NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "grading_periods" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id")
);

CREATE TABLE IF NOT EXISTS "grade_items" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "period_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "category_id" text NOT NULL,
  "assessment_id" text,
  "title" text NOT NULL,
  "maximum_marks" bigint NOT NULL,
  "due_on" text,
  "status" text NOT NULL DEFAULT 'open',
  "position" bigint NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "grading_periods" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("category_id") REFERENCES "grade_categories" ("id"),
  FOREIGN KEY ("assessment_id") REFERENCES "assessments" ("id")
);

CREATE TABLE IF NOT EXISTS "grade_entries" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "item_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "raw_marks" bigint,
  "adjusted_marks" bigint,
  "status" text NOT NULL DEFAULT 'missing',
  "adjustment_reason" text,
  "recorded_by_person_id" text NOT NULL,
  "recorded_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("item_id") REFERENCES "grade_items" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("recorded_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "gradebook_submissions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "period_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'open',
  "submitted_by_person_id" text,
  "submitted_at" text,
  "reviewed_by_person_id" text,
  "reviewed_at" text,
  "locked_at" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "grading_periods" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("submitted_by_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("reviewed_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "grading_scale_bands" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "period_id" text NOT NULL,
  "position" bigint NOT NULL,
  "minimum_tenths" bigint NOT NULL,
  "maximum_tenths" bigint NOT NULL,
  "grade" text NOT NULL,
  "remark" text NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "grading_periods" ("id")
);

CREATE TABLE IF NOT EXISTS "guardian_alerts" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "guardian_person_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "source_type" text NOT NULL,
  "source_id" text NOT NULL,
  "kind" text NOT NULL,
  "title" text NOT NULL,
  "message" text NOT NULL,
  "status" text NOT NULL DEFAULT 'issued',
  "issued_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "read_at" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("guardian_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "media_assets" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "uploaded_by_person_id" text NOT NULL,
  "kind" text NOT NULL,
  "original_filename" text NOT NULL,
  "content_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "object_key" text NOT NULL,
  "status" text NOT NULL DEFAULT 'ready',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("uploaded_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "interactive_activities" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "created_by_person_id" text NOT NULL,
  "title" text NOT NULL,
  "provider" text NOT NULL DEFAULT 'h5p',
  "content_type" text NOT NULL,
  "launch_url" text,
  "launch_origin" text,
  "package_asset_id" text,
  "runtime_content_id" text,
  "runtime_imported_at" text,
  "fallback_text" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'draft',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("package_asset_id") REFERENCES "media_assets" ("id")
);

CREATE TABLE IF NOT EXISTS "lessons" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "unit_id" text NOT NULL,
  "author_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "current_version" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("unit_id") REFERENCES "curriculum_units" ("id"),
  FOREIGN KEY ("author_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "interactive_activity_results" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "activity_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "lesson_id" text NOT NULL,
  "lesson_version" bigint NOT NULL,
  "verb" text NOT NULL,
  "score_percent" bigint,
  "success" bigint,
  "completion" bigint NOT NULL DEFAULT 0,
  "statement_json" text NOT NULL DEFAULT '{}',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("activity_id") REFERENCES "interactive_activities" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id")
);

CREATE TABLE IF NOT EXISTS "lesson_versions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "lesson_id" text NOT NULL,
  "version" bigint NOT NULL,
  "title" text NOT NULL,
  "summary" text NOT NULL DEFAULT '',
  "objectives" text NOT NULL DEFAULT '[]',
  "status" text NOT NULL DEFAULT 'draft',
  "published_at" text,
  "created_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "lesson_blocks" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "lesson_version_id" text NOT NULL,
  "type" text NOT NULL,
  "position" bigint NOT NULL,
  "title" text NOT NULL,
  "content" text NOT NULL DEFAULT '',
  "config" text NOT NULL DEFAULT '{}',
  "ready" bigint NOT NULL DEFAULT 0,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("lesson_version_id") REFERENCES "lesson_versions" ("id")
);

CREATE TABLE IF NOT EXISTS "lesson_progress" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "lesson_id" text NOT NULL,
  "lesson_version" bigint NOT NULL,
  "percent" bigint NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'in-progress',
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "completed_at" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id")
);

CREATE TABLE IF NOT EXISTS "lesson_release_rules" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "lesson_id" text NOT NULL,
  "available_from" text,
  "available_until" text,
  "prerequisite_lesson_id" text,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id"),
  FOREIGN KEY ("prerequisite_lesson_id") REFERENCES "lessons" ("id")
);

CREATE TABLE IF NOT EXISTS "lesson_standard_links" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "lesson_id" text NOT NULL,
  "standard_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id"),
  FOREIGN KEY ("standard_id") REFERENCES "curriculum_standards" ("id")
);

CREATE TABLE IF NOT EXISTS "message_threads" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "teacher_person_id" text NOT NULL,
  "offering_id" text,
  "started_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "last_message_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "learner_read_at" text,
  "teacher_read_at" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("teacher_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("started_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "message_reports" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "thread_id" text NOT NULL,
  "reported_by_person_id" text NOT NULL,
  "reason" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'open',
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "reviewed_by_person_id" text,
  "reviewed_at" text,
  "review_note" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("thread_id") REFERENCES "message_threads" ("id"),
  FOREIGN KEY ("reported_by_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("reviewed_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "thread_id" text NOT NULL,
  "sender_person_id" text NOT NULL,
  "body" text NOT NULL,
  "sent_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("thread_id") REFERENCES "message_threads" ("id"),
  FOREIGN KEY ("sender_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "report_cards" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "learner_person_id" text NOT NULL,
  "period_id" text NOT NULL,
  "class_group_id" text NOT NULL,
  "class_name" text NOT NULL,
  "status" text NOT NULL DEFAULT 'draft',
  "current_version" bigint NOT NULL DEFAULT 0,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  "updated_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("learner_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "grading_periods" ("id")
);

CREATE TABLE IF NOT EXISTS "report_card_versions" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "report_card_id" text NOT NULL,
  "version" bigint NOT NULL,
  "status" text NOT NULL,
  "overall_average_tenths" bigint NOT NULL,
  "attendance_present" bigint NOT NULL,
  "attendance_total" bigint NOT NULL,
  "conduct" text NOT NULL,
  "class_teacher_comment" text NOT NULL,
  "headteacher_comment" text NOT NULL,
  "promotion_decision" text NOT NULL,
  "next_term_begins_on" text,
  "submitted_at" text,
  "approved_by_person_id" text,
  "approved_at" text,
  "released_at" text,
  "created_by_person_id" text NOT NULL,
  "created_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("report_card_id") REFERENCES "report_cards" ("id"),
  FOREIGN KEY ("approved_by_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("created_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "report_subject_results" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "report_version_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "subject_code" text NOT NULL,
  "subject_name" text NOT NULL,
  "score_tenths" bigint NOT NULL,
  "grade" text NOT NULL,
  "remark" text NOT NULL,
  "teacher_comment" text NOT NULL,
  "position" bigint NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("report_version_id") REFERENCES "report_card_versions" ("id")
);

CREATE TABLE IF NOT EXISTS "rubric_criteria" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "assignment_version_id" text NOT NULL,
  "position" bigint NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "maximum_points" bigint NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("assignment_version_id") REFERENCES "assignment_versions" ("id")
);

CREATE TABLE IF NOT EXISTS "rubric_levels" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "criterion_id" text NOT NULL,
  "position" bigint NOT NULL,
  "name" text NOT NULL,
  "points" bigint NOT NULL,
  "descriptor" text NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("criterion_id") REFERENCES "rubric_criteria" ("id")
);

CREATE TABLE IF NOT EXISTS "rubric_scores" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "submission_id" text NOT NULL,
  "criterion_id" text NOT NULL,
  "points" bigint NOT NULL,
  "comment" text NOT NULL DEFAULT '',
  "marked_by_person_id" text NOT NULL,
  "marked_at" text NOT NULL,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("submission_id") REFERENCES "assignment_submissions" ("id"),
  FOREIGN KEY ("criterion_id") REFERENCES "rubric_criteria" ("id"),
  FOREIGN KEY ("marked_by_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "submission_attachments" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "submission_id" text NOT NULL,
  "media_asset_id" text NOT NULL,
  "uploaded_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("submission_id") REFERENCES "assignment_submissions" ("id"),
  FOREIGN KEY ("media_asset_id") REFERENCES "media_assets" ("id")
);

CREATE TABLE IF NOT EXISTS "teacher_assignments" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "offering_id" text NOT NULL,
  "teacher_person_id" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "assigned_at" text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("teacher_person_id") REFERENCES "people" ("id")
);

CREATE TABLE IF NOT EXISTS "timetable_periods" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "name" text NOT NULL,
  "position" bigint NOT NULL,
  "starts_at" text NOT NULL,
  "ends_at" text NOT NULL,
  "kind" text NOT NULL DEFAULT 'lesson',
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id")
);

CREATE TABLE IF NOT EXISTS "timetable_entries" (
  "id" text PRIMARY KEY,
  "tenant_id" text NOT NULL,
  "period_id" text NOT NULL,
  "weekday" bigint NOT NULL,
  "class_group_id" text NOT NULL,
  "offering_id" text,
  "teacher_person_id" text,
  "subject_name" text NOT NULL,
  "room" text NOT NULL,
  "status" text NOT NULL DEFAULT 'scheduled',
  "substitute_teacher_person_id" text,
  "change_reason" text,
  FOREIGN KEY ("tenant_id") REFERENCES "tenants" ("id"),
  FOREIGN KEY ("period_id") REFERENCES "timetable_periods" ("id"),
  FOREIGN KEY ("offering_id") REFERENCES "subject_offerings" ("id"),
  FOREIGN KEY ("teacher_person_id") REFERENCES "people" ("id"),
  FOREIGN KEY ("substitute_teacher_person_id") REFERENCES "people" ("id")
);

CREATE INDEX IF NOT EXISTS "attempts_learner_assessment_idx"
  ON "assessment_attempts" ("tenant_id", "learner_person_id", "assessment_id");

CREATE INDEX IF NOT EXISTS "attempts_marking_queue_idx"
  ON "assessment_attempts" ("tenant_id", "status", "updated_at");

CREATE UNIQUE INDEX IF NOT EXISTS "assessment_question_position_idx"
  ON "assessment_questions" ("assessment_version_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "response_attempt_question_idx"
  ON "assessment_responses" ("attempt_id", "question_version_id");

CREATE UNIQUE INDEX IF NOT EXISTS "assessment_version_number_idx"
  ON "assessment_versions" ("assessment_id", "version");

CREATE INDEX IF NOT EXISTS "assessments_tenant_offering_idx"
  ON "assessments" ("tenant_id", "offering_id", "status");

CREATE UNIQUE INDEX IF NOT EXISTS "submission_assignment_learner_idx"
  ON "assignment_submissions" ("assignment_id", "assignment_version", "learner_person_id");

CREATE INDEX IF NOT EXISTS "submission_marking_queue_idx"
  ON "assignment_submissions" ("tenant_id", "status", "updated_at");

CREATE UNIQUE INDEX IF NOT EXISTS "assignment_version_number_idx"
  ON "assignment_versions" ("assignment_id", "version");

CREATE INDEX IF NOT EXISTS "assignments_offering_status_idx"
  ON "assignments" ("tenant_id", "offering_id", "status");

CREATE INDEX IF NOT EXISTS "attendance_corrections_record_idx"
  ON "attendance_corrections" ("tenant_id", "attendance_record_id");

CREATE UNIQUE INDEX IF NOT EXISTS "attendance_session_learner_idx"
  ON "attendance_records" ("session_id", "learner_person_id");

CREATE INDEX IF NOT EXISTS "attendance_learner_idx"
  ON "attendance_records" ("tenant_id", "learner_person_id");

CREATE UNIQUE INDEX IF NOT EXISTS "attendance_class_date_mode_idx"
  ON "attendance_sessions" ("tenant_id", "class_group_id", "session_date", "mode");

CREATE UNIQUE INDEX IF NOT EXISTS "standards_offering_code_idx"
  ON "curriculum_standards" ("tenant_id", "offering_id", "code");

CREATE INDEX IF NOT EXISTS "standards_offering_position_idx"
  ON "curriculum_standards" ("tenant_id", "offering_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "units_offering_position_idx"
  ON "curriculum_units" ("offering_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "category_offering_position_idx"
  ON "grade_categories" ("period_id", "offering_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "grade_entry_item_learner_idx"
  ON "grade_entries" ("item_id", "learner_person_id");

CREATE INDEX IF NOT EXISTS "grade_entries_learner_idx"
  ON "grade_entries" ("tenant_id", "learner_person_id");

CREATE UNIQUE INDEX IF NOT EXISTS "grade_item_offering_position_idx"
  ON "grade_items" ("period_id", "offering_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "gradebook_period_offering_idx"
  ON "gradebook_submissions" ("tenant_id", "period_id", "offering_id");

CREATE UNIQUE INDEX IF NOT EXISTS "period_tenant_year_name_idx"
  ON "grading_periods" ("tenant_id", "academic_year_id", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "scale_period_position_idx"
  ON "grading_scale_bands" ("period_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "guardian_alert_source_idx"
  ON "guardian_alerts" ("tenant_id", "guardian_person_id", "source_type", "source_id", "kind");

CREATE INDEX IF NOT EXISTS "activities_tenant_offering_idx"
  ON "interactive_activities" ("tenant_id", "offering_id", "status");

CREATE INDEX IF NOT EXISTS "activity_results_learner_idx"
  ON "interactive_activity_results" ("tenant_id", "learner_person_id", "activity_id", "created_at");

CREATE UNIQUE INDEX IF NOT EXISTS "lesson_block_position_idx"
  ON "lesson_blocks" ("lesson_version_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "lesson_progress_learner_version_idx"
  ON "lesson_progress" ("tenant_id", "learner_person_id", "lesson_id", "lesson_version");

CREATE UNIQUE INDEX IF NOT EXISTS "lesson_release_rule_idx"
  ON "lesson_release_rules" ("tenant_id", "lesson_id");

CREATE INDEX IF NOT EXISTS "lesson_prerequisite_lookup_idx"
  ON "lesson_release_rules" ("tenant_id", "prerequisite_lesson_id");

CREATE UNIQUE INDEX IF NOT EXISTS "lesson_standard_link_idx"
  ON "lesson_standard_links" ("tenant_id", "lesson_id", "standard_id");

CREATE INDEX IF NOT EXISTS "standard_lesson_lookup_idx"
  ON "lesson_standard_links" ("tenant_id", "standard_id");

CREATE UNIQUE INDEX IF NOT EXISTS "lesson_version_number_idx"
  ON "lesson_versions" ("lesson_id", "version");

CREATE INDEX IF NOT EXISTS "lessons_tenant_offering_idx"
  ON "lessons" ("tenant_id", "offering_id", "status");

CREATE UNIQUE INDEX IF NOT EXISTS "media_object_key_idx"
  ON "media_assets" ("object_key");

CREATE INDEX IF NOT EXISTS "media_tenant_offering_idx"
  ON "media_assets" ("tenant_id", "offering_id", "status");

CREATE INDEX IF NOT EXISTS "reports_tenant_status_idx"
  ON "message_reports" ("tenant_id", "status");

CREATE INDEX IF NOT EXISTS "reports_thread_idx"
  ON "message_reports" ("thread_id");

CREATE INDEX IF NOT EXISTS "threads_learner_recent_idx"
  ON "message_threads" ("tenant_id", "learner_person_id", "last_message_at");

CREATE INDEX IF NOT EXISTS "threads_teacher_recent_idx"
  ON "message_threads" ("tenant_id", "teacher_person_id", "last_message_at");

CREATE INDEX IF NOT EXISTS "messages_thread_sent_idx"
  ON "messages" ("thread_id", "sent_at");

CREATE INDEX IF NOT EXISTS "questions_tenant_offering_idx"
  ON "question_bank_items" ("tenant_id", "offering_id", "status");

CREATE UNIQUE INDEX IF NOT EXISTS "question_version_number_idx"
  ON "question_versions" ("question_id", "version");

CREATE UNIQUE INDEX IF NOT EXISTS "report_version_number_idx"
  ON "report_card_versions" ("report_card_id", "version");

CREATE UNIQUE INDEX IF NOT EXISTS "report_learner_period_idx"
  ON "report_cards" ("tenant_id", "learner_person_id", "period_id");

CREATE UNIQUE INDEX IF NOT EXISTS "report_subject_position_idx"
  ON "report_subject_results" ("report_version_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "rubric_criterion_position_idx"
  ON "rubric_criteria" ("assignment_version_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "rubric_level_position_idx"
  ON "rubric_levels" ("criterion_id", "position");

CREATE UNIQUE INDEX IF NOT EXISTS "rubric_score_submission_criterion_idx"
  ON "rubric_scores" ("submission_id", "criterion_id");

CREATE INDEX IF NOT EXISTS "offerings_tenant_class_idx"
  ON "subject_offerings" ("tenant_id", "class_group_id");

CREATE UNIQUE INDEX IF NOT EXISTS "offerings_subject_class_year_idx"
  ON "subject_offerings" ("tenant_id", "subject_id", "class_group_id", "academic_year_id");

CREATE UNIQUE INDEX IF NOT EXISTS "subjects_tenant_code_idx"
  ON "subjects" ("tenant_id", "code");

CREATE UNIQUE INDEX IF NOT EXISTS "submission_attachment_asset_idx"
  ON "submission_attachments" ("submission_id", "media_asset_id");

CREATE INDEX IF NOT EXISTS "submission_attachment_submission_idx"
  ON "submission_attachments" ("tenant_id", "submission_id");

CREATE UNIQUE INDEX IF NOT EXISTS "teacher_offering_assignment_idx"
  ON "teacher_assignments" ("tenant_id", "offering_id", "teacher_person_id");

CREATE INDEX IF NOT EXISTS "timetable_class_day_idx"
  ON "timetable_entries" ("tenant_id", "class_group_id", "weekday");

CREATE INDEX IF NOT EXISTS "timetable_teacher_day_idx"
  ON "timetable_entries" ("tenant_id", "teacher_person_id", "weekday");

CREATE UNIQUE INDEX IF NOT EXISTS "timetable_period_position_idx"
  ON "timetable_periods" ("tenant_id", "position");`;
