import { writeFileSync } from "node:fs";
import { getTableConfig, type SQLiteTable } from "drizzle-orm/sqlite-core";
import { is } from "drizzle-orm";
import { SQLiteTable as SQLiteTableClass } from "drizzle-orm/sqlite-core";
import * as schema from "../db/schema";

/* ==========================================================================
   Learning schema generator

   db/schema.ts declares 48 tables for SQLite/D1. The VPS runs PostgreSQL, so
   those tables need PostgreSQL DDL. Hand-transcribing 48 tables is exactly the
   kind of work that produces a typo in one column three months from now, so
   the DDL is generated from the Drizzle definitions instead and committed.

   Regenerate after changing db/schema.ts:

     npx tsx scripts/generate-learning-schema.ts

   Storage types deliberately mirror SQLite rather than idiomatic PostgreSQL:
   timestamps stay `text` because the repositories write and read ISO strings
   and never compare them in SQL, and booleans stay `integer` because the
   repositories bind 1/0 and coerce with Boolean() on the way out. That keeps
   all 202 prepared statements working untouched. Tightening these types is a
   later change that has to move the read sites with it.
   ========================================================================== */

const HEADER = `/* Generated by scripts/generate-learning-schema.ts from db/schema.ts.
   Do not edit by hand: regenerate with

     npm run schema:generate

   Storage types mirror the SQLite originals on purpose — see the generator for
   why. Tables already created by db/postgres.ts are not repeated here.

   This is a TypeScript module rather than a .sql file so that it is bundled
   and traced like any other import. A .sql read at runtime through
   import.meta.url does not reliably survive the Next standalone build that
   the Docker image is built from. */

export const learningSchema = \``;

const FOOTER = "`;\n";

/* These eight already exist in db/postgres.ts, which owns the identity and
   admissions side of the database. Emitting them twice would give two
   definitions of the same table that could drift apart. */
const OWNED_BY_POSTGRES_MODULE = new Set([
  "admission_application_records",
  "audit_events",
  "guardian_relationships",
  "identity_accounts",
  "people",
  "tenant_bootstrap",
  "tenant_memberships",
  "tenants",
]);

function columnType(column: { getSQLType(): string; columnType: string }): string {
  const sqliteType = column.getSQLType().toLowerCase();
  if (sqliteType.startsWith("text")) return "text";
  if (sqliteType.startsWith("real")) return "double precision";
  if (sqliteType.startsWith("blob")) return "bytea";
  /* SQLite INTEGER is 64-bit. bigint keeps byte counts and epoch values safe,
     and node-postgres hands both back as JavaScript numbers for anything
     inside the safe integer range, which every value here is. */
  return "bigint";
}

function defaultClause(column: {
  default: unknown;
  hasDefault: boolean;
}): string {
  if (!column.hasDefault || column.default === undefined) return "";
  const value = column.default;
  if (value === null) return " DEFAULT NULL";
  if (typeof value === "boolean") return ` DEFAULT ${value ? 1 : 0}`;
  if (typeof value === "number") return ` DEFAULT ${value}`;
  if (typeof value === "string") return ` DEFAULT '${value.replace(/'/g, "''")}'`;
  /* sql`CURRENT_TIMESTAMP` and friends arrive as a SQL object. The only one
     used in this schema is CURRENT_TIMESTAMP. PostgreSQL has it, but casting
     it to text gives "2026-08-01 20:30:00.123456+00" where SQLite gives
     "2026-08-01 20:30:00" — so it is formatted to match SQLite exactly. Rows
     written before the port and after it should not be distinguishable. */
  return ` DEFAULT ${SQLITE_TIMESTAMP}`;
}

const SQLITE_TIMESTAMP =
  "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')";

function quote(identifier: string): string {
  return `"${identifier}"`;
}

const tableStatements = new Map<string, string>();
const indexStatements: string[] = [];
/* Table name -> the tables its foreign keys point at. PostgreSQL checks
   references at CREATE TABLE time, unlike SQLite, so the statements have to be
   emitted in dependency order. */
const dependencies = new Map<string, Set<string>>();

for (const exported of Object.values(schema)) {
  if (!is(exported, SQLiteTableClass)) continue;
  const table = getTableConfig(exported as SQLiteTable);
  if (OWNED_BY_POSTGRES_MODULE.has(table.name)) continue;

  const dependsOn = new Set<string>();
  const lines: string[] = [];

  for (const column of table.columns) {
    const parts = [quote(column.name), columnType(column)];
    if (column.primary) parts.push("PRIMARY KEY");
    if (column.notNull && !column.primary) parts.push("NOT NULL");
    const fallback = defaultClause(column);
    lines.push(`  ${parts.join(" ")}${fallback}`);
  }

  /* Composite primary keys are declared separately from the columns. */
  for (const primaryKey of table.primaryKeys) {
    const columns = primaryKey.columns.map((column) => quote(column.name));
    lines.push(`  PRIMARY KEY (${columns.join(", ")})`);
  }

  for (const unique of table.uniqueConstraints) {
    const columns = unique.columns.map((column) => quote(column.name));
    lines.push(`  UNIQUE (${columns.join(", ")})`);
  }

  /* Column-level .unique() shows up on the column rather than in
     uniqueConstraints, so it is picked up here. */
  for (const column of table.columns) {
    if (column.isUnique && !column.primary) {
      lines.push(`  UNIQUE (${quote(column.name)})`);
    }
  }

  for (const foreignKey of table.foreignKeys) {
    const reference = foreignKey.reference();
    const columns = reference.columns.map((column) => quote(column.name));
    const foreignColumns = reference.foreignColumns.map((column) =>
      quote(column.name),
    );
    const foreignTable = getTableConfig(
      reference.foreignTable as SQLiteTable,
    ).name;
    /* A self-reference is satisfied by the table being created, and the eight
       identity tables are already there from db/postgres.ts. Neither
       constrains ordering here. */
    if (
      foreignTable !== table.name &&
      !OWNED_BY_POSTGRES_MODULE.has(foreignTable)
    ) {
      dependsOn.add(foreignTable);
    }
    lines.push(
      `  FOREIGN KEY (${columns.join(", ")}) REFERENCES ${quote(foreignTable)} (${foreignColumns.join(", ")})`,
    );
  }

  dependencies.set(table.name, dependsOn);
  tableStatements.set(
    table.name,
    `CREATE TABLE IF NOT EXISTS ${quote(table.name)} (\n${lines.join(",\n")}\n);`,
  );

  for (const definition of table.indexes) {
    const config = definition.config;
    const columns = (config.columns as Array<{ name?: string }>)
      .map((column) => (column.name ? quote(column.name) : undefined))
      .filter((name): name is string => Boolean(name));
    if (columns.length === 0) continue;
    indexStatements.push(
      `CREATE ${config.unique ? "UNIQUE " : ""}INDEX IF NOT EXISTS ${quote(config.name)}\n  ON ${quote(table.name)} (${columns.join(", ")});`,
    );
  }
}

/* Depth-first topological sort. The schema has no reference cycles today; if
   one is ever introduced this throws rather than emitting DDL that fails
   halfway through a deployment. */
const ordered: string[] = [];
const settled = new Set<string>();
const visiting = new Set<string>();

function visit(name: string, trail: string[]): void {
  if (settled.has(name)) return;
  if (visiting.has(name)) {
    throw new Error(
      `Foreign key cycle: ${[...trail, name].join(" -> ")}. PostgreSQL cannot create these in one pass.`,
    );
  }
  visiting.add(name);
  for (const dependency of dependencies.get(name) ?? []) {
    if (!tableStatements.has(dependency)) {
      throw new Error(
        `${name} references ${dependency}, which is neither generated here nor created by db/postgres.ts.`,
      );
    }
    visit(dependency, [...trail, name]);
  }
  visiting.delete(name);
  settled.add(name);
  ordered.push(name);
}

for (const name of [...tableStatements.keys()].sort()) {
  visit(name, []);
}

const sql = [
  ordered.map((name) => tableStatements.get(name)).join("\n\n"),
  "",
  indexStatements.join("\n\n"),
].join("\n");

/* Backslashes and backticks would end the template literal early. Neither
   appears in generated DDL today; escaping them keeps that true if a default
   value ever contains one. */
const escaped = sql.replace(/[\\`]/g, "\\$&").replace(/\$\{/g, "\\${");

writeFileSync(
  new URL("../db/learning-schema.ts", import.meta.url),
  `${HEADER}${escaped}${FOOTER}`,
);
console.log(
  `Wrote ${ordered.length} tables and ${indexStatements.length} indexes to db/learning-schema.ts`,
);
